apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "xai-fulfillment.fullname" . }}
    namespace: {{ .Release.Namespace }}
data:
    SERVER_THREADS: "4"
    DATA_FOLDER_PATH: "agridatavalue"
    MODEL_FOLDER_PATH: "agridatavalue"
    EXPLAINER_FOLDER_PATH: "agridatavalue"
    SERVER_PORT: "8000"
    SECURE_STORE_ENDPOINT: "securestore-api.platform.agridatavalue.eu"
    STORE_ENDPOINT: "minio.store.platform.agridatavalue.eu"
    MINIO_SECURE: "true"
    TEMP: "/app/data_temp/"
