openapi: 3.0.3
info:
    title: ADV
    description: "TEST"
    version: 0.0.2
    contact:
        name: "Mirko Colageo"
        email: m.colageo@almaviva.it

paths:
    /build:
        post:
            summary: Build the explainer
            description: Build explainer for a given pilot
            operationId: build
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BuildRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BuildResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
            tags:
                - Build

    /feature-importance:
        post:
            summary: Return the feature importance data
            description: Return the feature importance data for a given pilot
            operationId: featureImportance
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/FeatureImportanceRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FeatureImportanceResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - featureImportance

    /feature-descriptions:
        post:
            summary: Return the feature descriptions
            description: Return the feature descriptions for a given pilot
            operationId: featureDescriptions
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/FeatureDescriptionRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FeatureDescriptionResponse"
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - featureDescriptions

    /model-performance-metric:
        post:
            summary: Return the model performance metric
            description: Return the model performance metric for a given pilot
            operationId: modelPerformanceMetric
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ModelPerformanceMetricRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ModelPerformanceMetricResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - modelPerformanceMetric

    /model-performance:
        post:
            summary: Return the model performance data
            description: Return the model performance data for a given pilot
            operationId: modelPerformance
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ModelPerformanceRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ModelPerformanceResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - modelPerformance

    /data-source:
        post:
            summary: Return the source of the data
            description: Return the summary of source data
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataSourceRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataSourceResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - modelPerformance

    /data-features-average-scores:
        post:
            summary: Return the average scores of the features
            description: Return the average scores of the features for a given pilot
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataFeatureAverageScoresRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataFeatureAverageScoresResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - data-card

    /data-distribution:
        post:
            summary: Return the distribution of the data
            description: Return the distribution of the data for a given pilot
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataDistributionRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DataDistributionResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error

    /ask:
        post:
            summary: Ask something to the explainer
            description: Returns an explaination string
            operationId: ask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AskRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AskResponse"
                "404":
                    description: Pilot / Explainer not found
            tags:
                - Ask

tags: []
servers: []
components:
    securitySchemes:
        bearer:
            scheme: bearer
            bearerFormat: Bearer
            description: "Please enter token in following format: Bearer <JWT>"
            type: http
    schemas:
        DataDistributionRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
                feature:
                    description: the feature name of the distribution data
                    type: string
            required:
                - model
                - feature
        DataDistributionResponse:
            type: object
            properties:
                name:
                    type: string
                data:
                    type: array
                    items:
                        type: number
                        format: float

        DataFeatureAverageScoresRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
            required:
                - model
        DataFeatureAverageScoresResponse:
            type: array
            items:
                type: object
                properties:
                    feature:
                        type: string
                    min-score:
                        type: number
                        format: float
                    max-score:
                        type: number
                        format: float
                    avarage-score:
                        type: number
                        format: float

        DataSourceRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
            required:
                - model
        DataSourceResponse:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
                    value:
                        type: number
                        format: float
            example:
                - name: "Soil"
                  value: 0.7
                - name: "Drone"
                  value: 0.2
                - name: "Satellite"
                  value: 0.1

        FeatureImportanceRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
            required:
                - model
                - pilot
        FeatureImportanceResponse:
            type: object
            properties:
                features:
                    type: array
                    items:
                        type: string
                importance:
                    type: string
                values:
                    type: array
                    items:
                        type: number
                        format: float

        FeatureDescriptionRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
            required:
                - model
        FeatureDescriptionResponse:
            type: array
            items:
                type: object
                properties:
                    feature:
                        type: string
                    description:
                        type: string
                example:
                    - feature: "Row distance (cm)"
                      description: "Distance between plantation rows in cm"
                    - feature: "NO3-N 0-30 cm start (kg/ha)"
                      description: "Nitrate content in the soil at 0-30 cm depth at the start of the season"

        ModelPerformanceMetricRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
            required:
                - model
        ModelPerformanceMetricResponse:
            oneOf:
                - $ref: "#/components/schemas/ImageModelPerformanceMetric"
                - $ref: "#/components/schemas/TabularModelPerformanceMetric"

        ModelPerformanceRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
            required:
                - model
        ModelPerformanceResponse:
            type: object
            properties:
                target:
                    type: string
                actual:
                    type: array
                    items:
                        type: number
                        format: float
                predictions:
                    type: array
                    items:
                        type: number
                        format: float

        BuildRequest:
            type: object
            properties:
                model:
                    description: path for the ML model file
                    example: "model.pkl"
                    type: string
                metadata:
                    description: path for the metadata file
                    example: "metadata.json"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
                data:
                    description: optional, the folder path where the data is stored
                    type: string
            required:
                - model
                - metadata
                - pilot
        BuildResponse:
            type: object
            properties:
                status:
                    type: string

        AskRequest:
            type: object
            properties:
                request:
                    description: request to ask to the explainer
                    example: ""
                    type: string
                explainer:
                    description: explainer name
                    example: "ALE"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
            required:
                - pilot
                - request
                - explainer
        AskResponse:
            type: object
            properties:
                response:
                    type: string

        ImageModelPerformanceMetric:
            type: object

        TabularModelPerformanceMetric:
            type: object
            properties:
                mse:
                    type: number
                    format: float
                R2:
                    type: number
                    format: float
                MAE:
                    type: number
                    format: float
                RMSE:
                    type: number
                    format: float
                MAPE:
                    type: number
                    format: float
