openapi: 3.0.3
info:
    title: ADV
    description: "TEST"
    version: 0.0.1
    contact:
        name: "Mirko Colageo"
        email: m.colageo@almaviva.it

paths:
    /build:
        post:
            summary: Initialize a LLM-AI session
            description: Returns a sessionId string
            operationId: connect
            parameters:
                - name: model
                  in: query
                  description: path for the ML model file
                  example: "model.pkl"
                  required: true
                  schema:
                      type: string
                - name: metadata
                  in: query
                  description: path for the metadata file
                  example: "metadata.json"
                  required: true
                  schema:
                      type: string
                - name: pilot
                  in: query
                  description: the identifier of the pilot
                  example: "pilot8"
                  required: true
                  schema:
                      type: string
                - name: data
                  in: query
                  description: TODO
                  required: False
                  schema:
                      type: string

            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BuildResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/BuildResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: UserID / OrganizationID not found
            tags:
                - Prompt

tags: []
servers: []
components:
    securitySchemes:
        bearer:
            scheme: bearer
            bearerFormat: Bearer
            description: "Please enter token in following format: Bearer <JWT>"
            type: http
    schemas:
        BuildResponse:
            type: object
            properties:
                status:
                    type: string
