openapi: 3.0.3
info:
    title: ADV
    description: "TEST"
    version: 0.0.2
    contact:
        name: "Mirko Colageo"
        email: m.colageo@almaviva.it

paths:
    /build:
        post:
            summary: Build the explainer
            description: Build explainer for a given pilot
            operationId: build
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BuildRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BuildResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
            tags:
                - Build

    /feature-importance:
        post:
            summary: Return the feature importance data
            description: Return the feature importance data for a given pilot
            operationId: featureImportance
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/FeatureImportanceRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FeatureImportanceResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - featureImportance

    /feature-descriptions:
        post:
            summary: Return the feature descriptions
            description: Return the feature descriptions for a given pilot
            operationId: featureDescriptions
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/FeatureDescriptionRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FeatureDescriptionResponse"
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - featureDescriptions

    /model-performance-metric:
        post:
            summary: Return the model performance metric
            description: Return the model performance metric for a given pilot
            operationId: modelPerformanceMetric
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ModelPerformanceMetricRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ModelPerformanceMetricResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - modelPerformanceMetric

    /model-performance:
        post:
            summary: Return the model performance data
            description: Return the model performance data for a given pilot
            operationId: modelPerformance
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ModelPerformanceRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ModelPerformanceResponse"
                "400":
                    description: Invalid IDs combination supplied
                "404":
                    description: Pilot / Model not found
                "500":
                    description: Internal server error
            tags:
                - modelPerformance

    /ask:
        post:
            summary: Ask something to the explainer
            description: Returns an explaination string
            operationId: ask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AskRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AskResponse"
                "404":
                    description: Pilot / Explainer not found
            tags:
                - Ask

    /feedback:
        get:
            summary: Return the list of questions based on the metadata provided
            description: Return the list of questions based on the metadata provided
            parameters:
                - name: model
                  in: query
                  required: true
                  description: "the identifier of the model file name"
                  example: "model.pkl"
                  schema:
                      type: string
                - name: prediction_target
                  in: query
                  required: true
                  description: "the name of the field target to explain the model"
                  example: "Biomass"
                  schema:
                      type: string
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/QuestionsResponse"
        post:
            summary: Receive the feedback from the user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/FeedbackRequest"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FeedbackResponse"

tags: []
servers: []
components:
    securitySchemes:
        bearer:
            scheme: bearer
            bearerFormat: Bearer
            description: "Please enter token in following format: Bearer <JWT>"
            type: http
    schemas:
        QuestionsResponse:
            type: object
            properties:
                questions:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: string
                            question:
                                type: string
                            answers:
                                type: object
                                properties:
                                    type:
                                        type: string
                                        enum:
                                            - radio
                                            - string
                                    values:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                label:
                                                    type: string
                                                value:
                                                    type: string

        FeedbackRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                prediction_target:
                    description: the name of the field target to explain the model
                    example: "Biomass"
                    type: string
                responses:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: string
                            answer:
                                type: string
            required:
                - meta_data
                - responses
        FeedbackResponse:
            type: object
            properties:
                status:
                    type: string

        FeatureImportanceRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                data:
                    description: the identifier of the data folder name
                    example: "crop"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
                prediction_target:
                    description: the name of the field target to explain the model
                    example: "Biomass"
                    type: string
            required:
                - data
                - model
                - meta_data
        FeatureImportanceResponse:
            type: object
            properties:
                data:
                    type: string

        FeatureDescriptionRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
            required:
                - model
        FeatureDescriptionResponse:
            type: array
            items:
                type: object
                properties:
                    feature:
                        type: string
                    description:
                        type: string

        ModelPerformanceMetricRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                prediction_target:
                    description: the name of the field target to explain the model
                    example: "Biomass"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
            required:
                - model
                - meta_data
        ModelPerformanceMetricResponse:
            type: array
            items:
                type: object
                properties:
                    key:
                        type: string
                    value:
                        type: number
                        format: float

        ModelPerformanceRequest:
            type: object
            properties:
                model:
                    description: the identifier of the model file name
                    example: "model.pkl"
                    type: string
                data:
                    description: the identifier of the data folder name
                    example: "crop"
                    type: string
                prediction_target:
                    description: the name of the field target to explain the model
                    example: "Biomass"
                    type: string
                meta_data:
                    description: the identifier of the metadata file name
                    example: "metadata.json"
                    type: string
            required:
                - data
                - model
                - meta_data
        ModelPerformanceResponse:
            type: object
            properties:
                target:
                    type: integer
                actual:
                    type: array
                    items:
                        type: number
                        format: float
                prediction:
                    type: array
                    items:
                        type: number
                        format: float

        BuildRequest:
            type: object
            properties:
                model:
                    description: path for the ML model file
                    example: "model.pkl"
                    type: string
                metadata:
                    description: path for the metadata file
                    example: "metadata.json"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
                data:
                    description: optional
                    type: string
                prediction_targets:
                    description: the field names target to explain the model (Optional)
                    example: ["Biomass"]
                    type: array
                    items:
                        type: string
            required:
                - model
                - metadata
                - pilot
        BuildResponse:
            type: object
            properties:
                status:
                    type: string

        AskRequest:
            type: object
            properties:
                request:
                    description: request to ask to the explainer
                    example: ""
                    type: string
                explainer:
                    description: explainer name
                    example: "ALE"
                    type: string
                pilot:
                    description: the identifier of the pilot
                    example: "pilot8"
                    type: string
            required:
                - pilot
                - request
                - explainer
        AskResponse:
            type: object
            properties:
                response:
                    type: string
