apiVersion: v1
kind: ConfigMap
metadata:
    name: xai-fulfillment
    namespace: agridatavalue
data:
    DATA_FOLDER_PATH: "datagen"
    MODEL_FOLDER_PATH: "models"
    EXPLAINER_FOLDER_PATH: "explanators"
    SERVER_PORT: "8505"
    SECURE_STORE_ENDPOINT: "securestore-api.platform.agridatavalue.eu"
    STORE_ENDPOINT: "minio.store.platform.agridatavalue.eu"
    TEMP: "/app/data_temp/"
