apiVersion: v1
kind: Secret
metadata:
    name: xai-fulfillment
    namespace: agridatavalue
type: Opaque
stringData:
  MINIO_PUBLIC_KEY: YWR2
  MINIO_PRIVATE_KEY: YWR2I3NpZSMyMDI0
  SECURE_STORE_ACCESS_KEY: YWR2
  SECURE_STORE_SECRET_KEY: YWR2I3NpZSMyMDI0
