apiVersion: apps/v1
kind: Deployment
metadata:
    name: xai-fulfillment
    namespace: agridatavalue
spec:
    replicas: 1
    selector:
        matchLabels:
            app: xai-fulfillment
    template:
        metadata:
            labels:
                app: xai-fulfillment
        spec:
            containers:
                - name: xai-fulfillment
                  image: registry.git.agridatavalue.eu/agridatavalue/platform-integration/xai-fulfillment:REGISTRY_IMAGE_TAG
                  ports:
                      - containerPort: 8000
                        protocol: TCP
                        name: http
                  env:
                      - name: MINIO_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: minio-keys-secret
                                key: MINIO_ENDPOINT
                      - name: MINIO_ACCESS_KEY
                        valueFrom:
                            secretKeyRef:
                                name: minio-keys-secret
                                key: MINIO_ACCESS_KEY
                      - name: MINIO_SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: minio-keys-secret
                                key: MINIO_SECRET_KEY
