#Same secret used in delivery

apiVersion: v1
kind: Secret
metadata:
  name: minio-keys-secret
  namespace: agridatavalue
type: Opaque
stringData:
  MINIO_ENDPOINT: ADDR:PORT
  MINIO_PUBLIC_KEY: ACC_KEY
  MINIO_PRIVATE_KEY: SEC_KEY
