#Same secret used in delivery

apiVersion: v1
kind: Secret
metadata:
    name: minio-keys-secret
    namespace: agridatavalue
type: Opaque
data:
    MINIO_ENDPOINT: c2VjdXJlc3RvcmUucGxhdGZvcm0uYWdyaWRhdGF2YWx1ZS5ldTo5MDAw
    MINIO_PUBLIC_KEY: aG1zNHpMcmtIanZvOWc2Nnl5Qms=
    MINIO_PRIVATE_KEY: a2hjd05oMGZmaGVmQkV0S2tocHo5Vzk0QlJ5MW9yN1Ezb2dZUWJQUw==
